export const carDetail = [
  {
    id: 1,
    carType: "hatchback",
    image:  require("./assets/images/BMWX3.png"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "BMW i Series",
    price: "69.9 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '18-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 2,
    carType: "suv",
    image: require("./assets/images/BMWX5.png"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "BMW X5",
    price: "76.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '19-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 3,
    carType: "sedan",
    image:  require("./assets/images/BMWX6.png"),
    imageInteriors: "shf",
    color: ["white", "brown"],
    name: "BMW M340i xDrive",
    price: "85.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '21-Apr-2022',
    isBooked: true,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 4,
    carType: "coupe",
    image: require("./assets/images/BMWX7.png"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "BMW 4 series",
    price: "90.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '27-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 5,
    carType: "suv",
    image: require("./assets/images/audi1.jpg"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "Audi A4",
    price: "42.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '28-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper. BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 6,
    carType: "sedan",
    image: require("./assets/images/audi2.jpg"),
    imageInteriors: "drf",
    color: ["white", "brown"],
    name: "Audi S3",
    price: "55.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '29-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 7,
    carType: "hatchback",
    image: require("./assets/images/audi3.jpg"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "Audi A3",
    price: "80.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '27-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
  {
    id: 8,
    carType: "coupe",
    image: require("./assets/images/audi7.jpg"),
    imageInteriors: "",
    color: ["white", "brown"],
    name: "Audi 5000S",
    price: "90.5 Lakhs",
    fuel_type: "Petrol and Diesel",
    engine_cc: "2993 to 2998C",
    torque: "450 to 620 Nm",
    acceleration: "5.5 to 6.5 seconds",
    top_speed: "230 to 243 kmph",
    date: '20-Apr-2022',
    isBooked: false,
    variant:
      "The BMW i Series is available in 2 Automatic Diesel variants and in a single Automatic Petrol variant : Petrol : X3 xDrive 30i Luxury Line Diesel : X3 xDrive 20d xLine and X3 xDrive 20d Luxury Line",
    exteriors:
      "This hatchback measures 4,922mm in length and has a 2,975mm wheelbase. Besides, BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.  BMW has given it a one-piece kidney grille with flashy chrome trimming and large air inlets in the front bumper.",
    interiors: [
      "X5 has a high-end cockpit Vernasca leather upholstery for the seats",
      "A panoramic sunroof",
      "Four-zone temperature control",
      "BMW display key",
      "heads-up display",
      "parking and reversing assistance",
      "Surround-view cameras and attentiveness attention",
    ],
  },
];
